// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngwdvchbayanisosawsn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nd2R2Y2hiYXlhbmlzb3Nhd3NuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMzAwNzIsImV4cCI6MjA2NzcwNjA3Mn0.sTObcETAo8etNfJ9OgWqGriqx66EH-xTvPn5td-Abqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});